version: '3'
services:
  geoserver:
    build:
      context: .
      args:
        - GEOSERVER_VERSION=${GEOSERVER_VERSION}
        - CORS_ENABLED=true
        - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
    ports:
      - "8080:${VIRTUAL_PORT}"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      - SKIP_DEMO_DATA=true
    restart: always
    volumes:
      - ${HOST_DATA_PATH}:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
      - ${HOST_SHARED_DATA_PATH}:${GEOSERVER_SHARED_DATA_DIR}
      # - ${HOST_LOG_PATH}:{GEOSERVER_LOG}
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU}
          memory: ${LIMIT_MEM}
    networks:
      - default

networks:
  default:
    name: "${NETWORK}"
    external: true


